apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
    uptest.upbound.io/timeout: "2400"
  name: dev1-eks-cluster
  labels:
    testing.upbound.io/example-name: example
spec:
  forProvider:
    region: us-east-1
    roleArnRef:
      name: dev1-eks-cluster-role
    vpcConfig:
      - subnetIdRefs:
          - name: dev1-subnet1
          - name: dev1-subnet2


---

apiVersion: eks.aws.upbound.io/v1beta1
kind: ClusterAuth
metadata:
  name: auth
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
spec:
  forProvider:
    region: us-east-1
    clusterNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
  writeConnectionSecretToRef:
    name: cluster-conn
    namespace: argocd



---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: dev1-eks-cluster-role
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }


---

apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: dev1-cluster-policy
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    roleRef:
      name: dev1-eks-cluster-role


---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: dev1-vpc
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
spec:
  forProvider:
    enableDnsHostnames: true
    region: us-east-1
    cidrBlock: 172.16.0.0/16
    tags:
      Name: dev1-vpc


---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: dev1-subnet1
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
spec:
  forProvider:
    region: us-east-1
    mapPublicIpOnLaunch: true
    availabilityZone: us-east-1b
    vpcIdRef:
      name: dev1-vpc
    cidrBlock: 172.16.10.0/24


---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: dev1-subnet2
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
spec:
  forProvider:
    region: us-east-1
    mapPublicIpOnLaunch: true
    availabilityZone: us-east-1c
    vpcIdRef:
      name: dev1-vpc
    cidrBlock: 172.16.11.0/24



---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: dev1-private-subnet
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1b
    vpcIdRef:
      name: dev1-vpc
    cidrBlock: 172.16.12.0/24


---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: dev1-routetable
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
spec:
  forProvider:
    region: us-east-1
    tags:
      Name: dev1-routetable
    vpcIdRef:
      name: dev1-vpc


---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: dev1-routetbl-ass
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
spec:
  forProvider:
    region: us-east-1
    routeTableIdRef:
      name: dev1-routetable
    subnetIdRef:
      name: dev1-private-subnet


---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: dev1-igw
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: dev1-vpc


---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: DefaultRouteTable
metadata:
  name: dev1-def-routetable
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
spec:
  forProvider:
    defaultRouteTableIdRef:
      name: dev1-vpc
    region: us-east-1
    route:
      - gatewayIdRef:
          name: dev1-igw
        cidrBlock: 0.0.0.0/0



---

apiVersion: ssm.aws.upbound.io/v1beta1
kind: Parameter
metadata:
  annotations:
    meta.upbound.io/example-id: ssm/v1beta1/parameter
  labels:
    testing.upbound.io/example-name: cluster-endpoint
  name: cluster-endpoint
spec:
  forProvider:
    region: us-east-1
    type: String
    tier: Standard
    valueSecretRef:
      key: endpoint
      name: cluster-conn
      namespace: crossplane-system

---

apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: default
spec:
  forProvider:
    region: us-east-1
    clusterNameRef: 
      name: dev1-eks-cluster
    nodeRoleArnRef:
      name: dev1-node-role
    subnetIdRefs:
      - name: dev1-subnet1
      - name: dev1-subnet2
    scalingConfig:
      - minSize: 1
        maxSize: 1
        desiredSize: 1

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: dev1-node-role
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
---

apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: dev1-node-policy
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    roleRef:
      name: dev1-node-role

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: dev1-node-policy-2
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    roleRef:
      name: dev1-node-role

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: dev1-node-policy-3
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    roleRef:
      name: dev1-node-role

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: dev1-node-policy-4
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEC2RoleforSSM
    roleRef:
      name: dev1-node-role

---