apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bucket
spec:
  destination:
    name: in-cluster
    namespace: crossplane-system
    server: ''
  source:
    path: ./deploy-infra
    repoURL: 'https://github.com/vanzylg/platform.git'
    targetRevision: HEAD
  project: default
